package mocks

import "github.com/stretchr/testify/mock"

// This is an autogenerated mock type for the Gamer type
type Gamer struct {
	mock.Mock
}

// Play provides a mock function with given fields: args
func (_m *Gamer) Play(args ...string) {
	_m.Called(args)
}
