// Automatically generated by MockGen. DO NOT EDIT!
// Source: interfaces/gamer.go

package mock_interfaces

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Gamer interface
type MockGamer struct {
	ctrl     *gomock.Controller
	recorder *_MockGamerRecorder
}

// Recorder for MockGamer (not exported)
type _MockGamerRecorder struct {
	mock *MockGamer
}

func NewMockGamer(ctrl *gomock.Controller) *MockGamer {
	mock := &MockGamer{ctrl: ctrl}
	mock.recorder = &_MockGamerRecorder{mock}
	return mock
}

func (_m *MockGamer) EXPECT() *_MockGamerRecorder {
	return _m.recorder
}

func (_m *MockGamer) Play(args ...string) {
	_s := []interface{}{}
	for _, _x := range args {
		_s = append(_s, _x)
	}
	_m.ctrl.Call(_m, "Play", _s...)
}

func (_mr *_MockGamerRecorder) Play(arg0 ...interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Play", arg0...)
}
